# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHyNtUEm4s0hAHEwib7mE3qi8fVjQnt7
"""

import pandas as pd
import numpy as np
import re
import nltk
import time
import json

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import StackingClassifier

from scipy.sparse import hstack

nltk.download('punkt')
nltk.download('stopwords')

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

import pandas as pd

df = pd.read_json('/content/Sarcasm_Headlines_Dataset_v2.json', lines=True)

df = df[['headline', 'is_sarcastic']]
df.columns = ['text', 'label']

print("Total samples:", len(df))
df.head()

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^\w\s]", "", text)

    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]

    return " ".join(tokens)

df['clean_text'] = df['text'].apply(preprocess)

def add_features(text):
    return [
        text.count("!"),
        text.count("?"),
        sum(1 for c in text if c.isupper())
    ]

extra_features = np.array([add_features(t) for t in df['text']])

vectorizer = TfidfVectorizer(ngram_range=(1,2), max_features=5000)

X_text = vectorizer.fit_transform(df['clean_text'])

X = hstack([X_text, extra_features])
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

start_train = time.time()

base_models = [
    ('svm', SVC(probability=True)),
    ('lr', LogisticRegression()),
    ('nb', MultinomialNB())
]

meta_model = LogisticRegression()

stacking_model = StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=3
)

stacking_model.fit(X_train, y_train)

print("Training time:", round(time.time() - start_train, 2), "seconds")

y_pred = stacking_model.predict(X_test)

print("Stacking Model Results:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

sample_texts = [
    "Oh great, another Monday morning!",
    "The government passed a new law today."
]

sample_df = pd.DataFrame(sample_texts, columns=["text"])

sample_df['clean_text'] = sample_df['text'].apply(preprocess)

sample_extra = np.array([add_features(t) for t in sample_df['text']])

sample_X_text = vectorizer.transform(sample_df['clean_text'])
sample_X = hstack([sample_X_text, sample_extra])

sample_df['prediction'] = stacking_model.predict(sample_X)

sample_df

import joblib

# Save model
joblib.dump(stacking_model, 'stacking_model.pkl')

# Save vectorizer
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

from google.colab import files

files.download('stacking_model.pkl')
files.download('tfidf_vectorizer.pkl')